#!/bin/bash
# setup-local-hosts.sh — run on your LOCAL driver
# Parses CloudLab manifest.xml and adds nodeN entries to /etc/hosts

set -euo pipefail

MANIFEST="${1:-manifest.xml}"
[[ -f "$MANIFEST" ]] || { echo "❌ Manifest not found: $MANIFEST"; exit 1; }

echo "=== Parsing $MANIFEST ==="

# Use Python for reliable XML namespace handling
MAPPINGS=$(python3 - "$MANIFEST" <<'PY'
import sys, re, socket
import xml.etree.ElementTree as ET

tree = ET.parse(sys.argv[1])
root = tree.getroot()

# Strip XML namespace from tags so we can search easily
for elem in root.iter():
    elem.tag = re.sub(r'^\{.*\}', '', elem.tag)

entries = []
for node in root.iter('node'):
    client_id = node.get('client_id')  # e.g. "node1"
    if not client_id:
        continue

    # Find external login hostname (used for ssh from driver)
    login_host = None
    for svc in node.iter('login'):
        login_host = svc.get('hostname')
        if login_host:
            break

    if not login_host:
        # Fallback: <host name="..."/>
        host_elem = node.find('host')
        if host_elem is not None:
            login_host = host_elem.get('name')

    if not login_host:
        print(f"# WARN: no hostname for {client_id}", file=sys.stderr)
        continue

    # Resolve to IP
    try:
        ip = socket.gethostbyname(login_host)
    except socket.gaierror:
        print(f"# WARN: cannot resolve {login_host}", file=sys.stderr)
        continue

    entries.append((client_id, ip, login_host))

# Sort by node number
entries.sort(key=lambda e: int(re.search(r'\d+', e[0]).group()))
for client_id, ip, host in entries:
    print(f"{ip}\t{client_id}\t# {host}")
PY
)

if [[ -z "$MAPPINGS" ]]; then
    echo "❌ No mappings extracted from manifest"
    exit 1
fi

echo
echo "Discovered mappings:"
echo "$MAPPINGS"
echo

# -----------------------------------------------------------------------------
# Update /etc/hosts on driver
# -----------------------------------------------------------------------------
BLOCK_BEGIN="# BEGIN CLOUDLAB CLUSTER"
BLOCK_END="# END CLOUDLAB CLUSTER"

TMP=$(mktemp)
{
    echo "$BLOCK_BEGIN"
    echo "# Auto-generated by setup-local-hosts.sh from $MANIFEST"
    echo "# Generated: $(date)"
    echo "$MAPPINGS"
    echo "$BLOCK_END"
} > "$TMP"

echo "Updating /etc/hosts (requires sudo)..."

# Remove any prior block + legacy entries
sudo sed -i.bak "/$BLOCK_BEGIN/,/$BLOCK_END/d" /etc/hosts
sudo sed -i '/# BEGIN CHIMERA/,/# END CHIMERA/d' /etc/hosts 2>/dev/null || true

# Append fresh block
sudo bash -c "cat '$TMP' >> /etc/hosts"
rm -f "$TMP"

echo "✅ /etc/hosts updated."
echo
echo "Current cluster block:"
sed -n "/$BLOCK_BEGIN/,/$BLOCK_END/p" /etc/hosts
echo

# -----------------------------------------------------------------------------
# Sanity check
# -----------------------------------------------------------------------------
echo "Testing resolution..."
for line in $(echo "$MAPPINGS" | awk '{print $2}'); do
    if getent hosts "$line" >/dev/null; then
        echo "  ✓ $line resolves"
    else
        echo "  ✗ $line FAILED"
    fi
done

echo
echo "=== Done. You can now use 'ssh nodeN' from this machine. ==="