#!/bin/bash

# Usage: ./update_swarm_ssh.sh [manifest.xml] [optional_max_nodes]

# Path to your CloudLab manifest
MANIFEST="${1:-~/manifest.xml}"
USER="adb321"
SSH_CONFIG="$HOME/.ssh/config"

# Check if manifest exists
if [[ ! -f "$MANIFEST" ]]; then
    echo "❌ Manifest file not found: $MANIFEST"
    echo "Usage: $0 [path-to-manifest.xml] [max_nodes]"
    exit 1
fi

echo "📋 Parsing CloudLab manifest by node structure..."

# --- ROBUST MANIFEST PARSING ---
# 1. Finds all <node entries and captures their client_id (e.g., node0, node1)
# 2. Extracts the matching login hostname specifically bound within that node section
# 3. Sorts numerically by the node index number so node0 is always first
HOSTNAMES=()
while read -r node_idx hostname; do
    if [[ -n "$hostname" ]]; then
        HOSTNAMES+=("$hostname")
    fi
done < <(grep -E '<node|<login' "$MANIFEST" | awk -v usr="$USER" '
    /<node/ {
        # Extract the node number from client_id="nodeX"
        match($0, /client_id="node([0-9]+)"/, m)
        idx = m[1]
    }
    /<login/ && $0 ~ "username=\"" usr "\"" {
        # Extract the hostname for this specific node block
        match($0, /hostname="([^"]+)"/, h)
        if (idx != "") {
            print idx, h[1]
            idx = "" # Clear to prevent cross-contamination
        }
    }
' | sort -n -k1,1)

TOTAL_FOUND=${#HOSTNAMES[@]}

# If a second argument is provided, use it as a limit. 
# Otherwise, use every node found in the manifest.
MAX_NODES="${2:-$TOTAL_FOUND}"

if [[ $TOTAL_FOUND -eq 0 ]]; then
    echo "❌ No hostnames found for user $USER associated with client_id nodes in $MANIFEST"
    exit 1
fi

# Apply the limit if necessary
if [[ $TOTAL_FOUND -gt $MAX_NODES ]]; then
    echo "⚠️  Found $TOTAL_FOUND nodes, limiting to first $MAX_NODES as requested."
    HOSTNAMES=("${HOSTNAMES[@]:0:$MAX_NODES}")
else
    echo "✓ Found $TOTAL_FOUND nodes. Using all of them."
fi

# Backup existing config
BACKUP_FILE="$SSH_CONFIG.backup.$(date +%s)"
cp "$SSH_CONFIG" "$BACKUP_FILE"
echo "📦 SSH Config backed up to: $BACKUP_FILE"

# --- SMART CONFIG REBUILD ---
cat > "$SSH_CONFIG.tmp" << 'EOF'
# --- GLOBAL SETTINGS ---
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    LogLevel ERROR

# --- STATIC HOSTS ---
Host luigi
    HostName luigi.cse.lehigh.edu
    User amanda
    Port 22

# --- DYNAMIC CHIMERA CLUSTER (w1, w2, ...) ---
EOF

# Add the new w* entries maintaining exact node index order
for i in "${!HOSTNAMES[@]}"; do
    num=$((i + 1))
    cat >> "$SSH_CONFIG.tmp" << EOF
Host w$num
    HostName ${HOSTNAMES[$i]}
    User $USER

EOF
done

# Atomically replace the config
mv "$SSH_CONFIG.tmp" "$SSH_CONFIG"

echo "✅ SSH config updated with ${#HOSTNAMES[@]} nodes (w1 to w${#HOSTNAMES[@]})"
echo ""
echo "Current Mappings:"
for i in "${!HOSTNAMES[@]}"; do
    num=$((i + 1))
    printf "  w%-2d → node%d (%s)\n" $num $i "${HOSTNAMES[$i]}"
done
wait


echo "=== Chimera/Swarm-KV Hosts File & SSH Key Updater ==="
echo

# Detect nodes from SSH config
NODES=($(grep -iP "^Host w\d+$" ~/.ssh/config | awk '{print $2}' | sort -V))
NUM_NODES=${#NODES[@]}

# Path to your cluster public key
PUB_KEY="$HOME/.ssh/id_rsa.pub"

if [[ ! -f "$PUB_KEY" ]]; then
    echo "❌ Local public key not found at $PUB_KEY"
    echo "Please ensure your key pair is generated before running this script."
    exit 1
fi

# Array to store discovered nodes
declare -A NODE_IPS
declare -A NODE_NAMES

# Step 1: Push Keys and Discover Node Mappings
echo "Step 1: Authorizing SSH keys and discovering mappings on $NUM_NODES nodes..."
for node in "${NODES[@]}"; do
  echo -n "  Configuring $node... "
  
  # Inject public key to authorize passwordless cluster talk
  cat "$PUB_KEY" | ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 "$node" \
    "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys" 2>/dev/null || true

  # Get IP address dynamically filtering specifically for the 10.10.1.x subnet
  IP=$(ssh -o LogLevel=QUIET -o ConnectTimeout=3 "$node" "ip -o -4 addr show | grep 'inet 10.10.1.' | awk '{print \$4}' | cut -d/ -f1 | head -n 1" 2>/dev/null || true)
  
  # Get short hostname (node0, node1, etc.)
  HOSTNAME=$(ssh -o LogLevel=QUIET -o ConnectTimeout=3 "$node" "hostname -s" 2>/dev/null || true)
  
  if [[ -z "$IP" ]]; then
    echo "⚠️  Skipping $node (Unresponsive or missing 10.10.1.x IP)"
    continue
  fi

  NODE_IPS[$node]=$IP
  NODE_NAMES[$node]=$HOSTNAME
  
  echo "Authorized key & mapped to $HOSTNAME ($IP)"
done

echo

# Step 2: Create hosts file
echo "Step 2: Creating hosts file..."
HOSTS_FILE="/tmp/hosts_swarm_$$"

# We place a definitive block header and footer to make cleanup flawless
cat > "$HOSTS_FILE" <<EOF
# BEGIN CLUSTER MAPPINGS
# Auto-generated by update-hosts.sh
EOF

for node in "${NODES[@]}"; do
  if [[ -n "${NODE_IPS[$node]}" ]]; then
    echo "${NODE_IPS[$node]} $node swarm-$node ${NODE_NAMES[$node]}" >> "$HOSTS_FILE"
  fi
done

cat >> "$HOSTS_FILE" <<EOF
# END CLUSTER MAPPINGS
EOF

echo "Generated hosts file contents:"
cat "$HOSTS_FILE"
echo

# Step 3: Deploy hosts map to all nodes
echo "Step 3: Deploying hosts map to all nodes..."
for node in "${NODES[@]}"; do
  if [[ -z "${NODE_IPS[$node]}" ]]; then continue; fi
  echo -n "  Updating /etc/hosts on $node... "
  
  # Send our clean tmp hosts map over
  scp -q "$HOSTS_FILE" "$node":/tmp/hosts_swarm
  
  # Target the block using sed to strip old dynamic sections completely and cleanly append new ones
  ssh -o LogLevel=QUIET "$node" "sudo sed -i '/# BEGIN CHIMERA/,/# END CHIMERA/d' /etc/hosts" 2>/dev/null || true
  ssh -o LogLevel=QUIET "$node" "sudo sed -i '/swarm-w/d' /etc/hosts" 2>/dev/null || true # Legacy cleanup catch
  
  ssh -o LogLevel=QUIET "$node" "sudo bash -c 'cat /tmp/hosts_swarm >> /etc/hosts'"
  ssh -o LogLevel=QUIET "$node" "rm -f /tmp/hosts_swarm"
  
  echo "✓"
done

# Step 4: Update local coordinator node's gateway hosts
echo -n "  Updating local coordinator hosts file... "
sudo sed -i '/# BEGIN CHIMERA/,/# END CHIMERA/d' /etc/hosts 2>/dev/null || true
sudo sed -i '/swarm-w/d' /etc/hosts 2>/dev/null || true # Legacy cleanup catch
sudo bash -c "cat $HOSTS_FILE >> /etc/hosts"
echo "✓"


# # Step 5: Clean up conflicting default system services
# echo -e "\nStep 5: Cleaning up conflicting default memcached instances..."
# for node in "${NODES[@]}"; do
#   if [[ -z "${NODE_IPS[$node]}" ]]; then continue; fi
#   echo -n "  Stopping background memcached on $node... "
#   ssh -o LogLevel=QUIET "$node" "sudo systemctl stop memcached 2>/dev/null || true; sudo systemctl disable memcached 2>/dev/null || true; sudo pkill -9 -x memcached 2>/dev/null || true"
#   echo "✓"
# done

# Cleanup temporary local map
rm -f "$HOSTS_FILE"

echo
echo "=== ✓ All keys synced and hosts updated successfully over the 10.10.1.x network! ==="